on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dkaser/unraid-plugin-release-action@main
        with:
          plugin_version: ${{ github.event.release.name }}
          tag_name: ${{ github.event.release.tag_name }}
          plugin_changelog: ${{ github.event.release.body }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ github.event.release.upload_url }}
          composer_dir: "src/usr/local/php/plugin-name/"
