on:
  release:
    types:
      - prereleased
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Release Action
        uses: dkaser/unraid-plugin-release-action@main
        id: release_action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          composer_dir: "src/usr/local/php/plugin-name/"
          go_dir: "fileactivity-watcher"
          build_prereleases: true
          build_script: |
            cd fileactivity-watcher
            ./build.sh

      # # Print out the commit SHA
      # - name: Print commit SHA
      #   run: echo "Commit SHA ${{ steps.release_action.outputs.commit_long_sha }}"

      - name: Notify Discord
        uses: dkaser/discord-webhook-notify@main
        with:
          webhookUrl: ${{ secrets.TEST_DISCORD_WEBHOOK }}
          username: Tailscale Bot
          avatarUrl: https://raw.githubusercontent.com/unraid/unraid-tailscale/refs/heads/trunk/logo.png
          title: |
            🚀 **Tailscale Plugin : ${{ github.event.release.name }}**
          severity: info
          color: '#00ff00'
          description: |
            ## Changelog

            ${{ github.event.release.body }}
          linkUrl: ${{ github.event.release.html_url }}
          fields: |
            [
              {"name": "Released by", "value": ${{ toJson(github.event.release.author.login) }}, "inline": true},
              {"name": "Status", "value": ${{ toJson(github.event.release.prerelease && 'Preview' || 'Release') }}, "inline": true}
            ]
