on:
  release:
    types:
      - prereleased
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Release Action
        uses: dkaser/unraid-plugin-release-action@main
        id: release_action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # composer_dir: "src/usr/local/php/plugin-name/"
          # go_dir: "fileactivity-watcher"
          build_prereleases: true
          # build_script: |
          #   cd fileactivity-watcher
          #   ./build.sh

      # # Print out the commit SHA
      # - name: Print commit SHA
      #   run: echo "Commit SHA ${{ steps.release_action.outputs.commit_long_sha }}"

      - name: Notify Discord
        uses: dkaser/discord-webhook-notify@main
        with:
          webhookUrl: ${{ secrets.TEST_DISCORD_WEBHOOK }}
          username: Tailscale Bot
          avatarUrl: https://raw.githubusercontent.com/unraid/unraid-tailscale/refs/heads/trunk/logo.png
          thumbnailUrl: https://raw.githubusercontent.com/unraid/unraid-tailscale/refs/heads/trunk/logo.png
          severity: info
          color: '#00ff00'
          title: New Update Available
          description: |
            ## :loudspeaker: Tailscale Plugin Update : ${{ github.event.release.name }}

            ### :wrench: Changes

            ${{ github.event.release.body }}
          fields: |
            [
              {"name": ":wrench: Changes", "value": ${{ toJson(github.event.release.body) }} },
              {"name": "Channel", "value": ${{ toJson(github.event.release.prerelease && ':test_tube: Preview' || 'Release') }}, "inline": true},
              {"name": ":label: Tag", "value": ${{ toJson(github.event.release.tag_name) }}, "inline": true},
              {"name": ":link: Github Link", "value": ${{ toJson(github.event.release.html_url) }} }
            ]
